[build]
buildCommand = "composer install --optimize-autoloader --no-scripts --no-interaction --ignore-platform-req=ext-pcntl && npm install && npm run build"

[deploy]
startCommand = "bash /app/start.sh"
